name: GitRDP

on: workflow_dispatch

jobs:

  build:

    runs-on: windows-latest

    timeout-minutes: 999999999

    steps:

    - name: Copy NSSM & Ngrok to Windows Directory.

      run: | 

        Invoke-WebRequest https://dl.uploadgram.me/61275eff94aadg?raw -OutFile ngrok.exe

        Invoke-WebRequest https://dl.uploadgram.me/61275fc715b4bg?raw -OutFile nssm.exe

        Invoke-WebRequest https://dl.uploadgram.me/612761c538be2g?raw -OutFile DisablePasswordComplexity.ps1

        Invoke-WebRequest https://dl.uploadgram.me/61276167c5368g?raw -OutFile NGROK-US.bat

        Invoke-WebRequest https://dl.uploadgram.me/6127615a33cecg?raw -OutFile NGROK-AP.bat

        Invoke-WebRequest https://dl.uploadgram.me/6127617135ef4g?raw -OutFile NGROK-CHECK.bat

        Invoke-WebRequest https://dl.uploadgram.me/61276415f12ddg?raw -OutFile loop.bat

        copy nssm.exe C:\Windows\System32

        copy ngrok.exe C:\Windows\System32

    - name: Connect your NGROK account

      run: .\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN

      env:

        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Make YML file for NGROK.
      run: start NGROK-US.bat
    - name: Enable RDP Access.
      run: | 
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    - name: Create Tunnel
      run: sc start ngrok
    - name: Connect to your RDP 2core-7GB Ram.
      run: cmd /c NGROK-CHECK.bat
    - name: All Done! You can close Tab now! Maximum VM time:6h.
      run: cmd /c loop.bat 
